// Public surface of @skillcdn/db. Other workspaces import from this entry point only.
export { createDatabase, type Database, type DatabaseOptions } from "./client.js";
export { getSchemaStatus, migrateDatabase, type SchemaStatus } from "./migrate.js";
export { createBlobStore } from "./queries/blobs.js";
export {
  countEntries,
  type DirectoryListing,
  type EntryListing,
  type EntryRecord,
  findSkills,
  getEntry,
  getManifest,
  getSkillsAt,
  listDirectory,
  listEntries,
  listListedSkills,
  listSkillFiles,
  listSkillResources,
  searchEntries,
  servedEntries,
} from "./queries/entries.js";
export {
  listOperatorImages,
  type OperatorImageInput,
  type OperatorImageRecord,
  type PutOperatorImageResult,
  putOperatorImage,
  removeOperatorImage,
} from "./queries/images.js";
export {
  getLegalDocument,
  type LegalDocumentInput,
  type LegalDocumentRecord,
  listLegalDocuments,
  putLegalDocument,
  removeLegalDocument,
} from "./queries/legal.js";
export {
  countUnusedOAuthClients,
  createOAuthGrant,
  deleteExpiredOAuth,
  deleteOAuthGrant,
  deleteUnusedOAuthClients,
  findOAuthAccess,
  findOAuthClient,
  listOAuthGrants,
  type OAuthAccess,
  type OAuthClientAuthMethod,
  type OAuthClientInput,
  type OAuthClientRecord,
  type OAuthClientSource,
  type OAuthCodeRecord,
  type OAuthGrantInput,
  type OAuthGrantRecord,
  type OAuthRefreshOutcome,
  type OAuthTokenPair,
  revokeOAuthToken,
  rotateOAuthRefresh,
  saveOAuthClient,
  saveOAuthCode,
  takeOAuthCode,
  touchOAuthGrant,
} from "./queries/oauth.js";
export {
  addOperatorRepository,
  listOperatorRepositories,
  OPERATOR_LIST_KINDS,
  type OperatorListKind,
  type OperatorRepository,
  type PurgeResult,
  purgeRepository,
  removeOperatorRepository,
} from "./queries/operator.js";
export { type IndexedRepository, listIndexedRepositories } from "./queries/owners.js";
export {
  deleteStaleRepoPermissions,
  findReadableRepo,
  findRepoPermission,
  type ReadableRepo,
  type RepoPermission,
  type RepoPermissionScope,
  saveRepoPermission,
} from "./queries/permissions.js";
export {
  type CachedRef,
  deleteRepoAlias,
  deleteStaleMissingRepos,
  findCachedRef,
  findMissingRepo,
  findRepoByAlias,
  markRepositoryNotPublic,
  type RepoAlias,
  type RepoAliasRecord,
  type RepoRecord,
  type RepoScope,
  saveCachedRef,
  saveMissingRepo,
  saveRepository,
} from "./queries/repos.js";
export {
  getOperatorMedia,
  listOperatorMedia,
  listShowcaseEntries,
  type NewOperatorMedia,
  type OperatorMediaRecord,
  type PutShowcaseResult,
  putOperatorMedia,
  putShowcaseEntry,
  removeOperatorMedia,
  removeShowcaseEntry,
  type ShowcaseEntryInput,
  type ShowcaseEntryRecord,
  type StoredOperatorMedia,
} from "./queries/showcase.js";
export {
  claimSnapshot,
  ensureSnapshot,
  failSnapshot,
  getSnapshot,
  getSnapshotDiagnostics,
  type NewIndexEntry,
  releaseSnapshot,
  renewSnapshotLease,
  type SnapshotIndex,
  type SnapshotRecord,
  type SnapshotScope,
  type SnapshotStatus,
  writeSnapshotIndex,
} from "./queries/snapshots.js";
export {
  addUsage,
  addUsageClients,
  foldUsageClients,
  getRepoUsage,
  listTopRepositories,
  type RepositoryUsage,
  type UsageClient,
  type UsageDay,
  type UsageIncrement,
  type UsageMetric,
  type UsageTotal,
  usageDayOf,
} from "./queries/usage.js";
export {
  createSession,
  deleteExpiredSessions,
  deleteSession,
  deleteUserCredentials,
  findSession,
  findUser,
  forgetUserAccess,
  getUserCredentials,
  type SessionRecord,
  type StoredCredentials,
  saveLogin,
  saveUserCredentials,
  touchSession,
  type UserRecord,
} from "./queries/users.js";
export type { SkillFrontMatter, SnapshotDiagnostic, StoredTranslation } from "./schema.js";
