// Public surface of @skillcdn/core. Other workspaces import from this entry point only.

export { isAnonymouslyReadable } from "./access.js";
export {
  type Address,
  type AddressError,
  type AddressErrorCode,
  type AddressRef,
  formatAddress,
  formatOwnerPath,
  GIT_HOST_KEYS,
  type GitHostKey,
  isPinnedAddress,
  MAX_ADDRESS_LENGTH,
  type OwnerPath,
  parseAddress,
  parseOwnerPath,
} from "./address.js";
export { browseCatalogFiles, type CatalogFile, folderOverview } from "./browse-tree.js";
export { decodeText } from "./bytes.js";
export { contextPage } from "./context-page.js";
export { DomainError } from "./errors.js";
export {
  type FrontMatterError,
  type FrontMatterErrorCode,
  type FrontMatterSplit,
  MAX_FRONT_MATTER_LENGTH,
  parseFrontMatter,
  splitFrontMatter,
} from "./front-matter.js";
export { isFullCommitHash, isValidRefName, MAX_REF_LENGTH } from "./git-ref.js";
export { accountAvatarUrl, accountPageUrl, rawFileUrl } from "./host-urls.js";
export { isImageUrl, MAX_IMAGE_URL_LENGTH } from "./image-source.js";
export {
  classifyLicenseField,
  classifyLicenseFile,
  classifyLicenseText,
  describeLicense,
  isLicenseFileName,
  type LicensedEntry,
  type LicenseFact,
  type LicenseKind,
  type LicenseSources,
  licenseOfPath,
  MAX_LICENSE_TEXT_LENGTH,
  NO_LICENSE,
  preferredLicenseFile,
  resolveLicense,
  servesInFull,
  sourceFileUrl,
} from "./license.js";
export { isLanguageTag, MAX_TRANSLATIONS } from "./manifest-fields.js";
export { type MarkdownSummary, summarizeMarkdown } from "./markdown.js";
export {
  extractMarkdownReferences,
  inspectMarkdownReferences,
  MAX_LINK_MARKDOWN_LENGTH,
  MAX_MARKDOWN_REFERENCES,
  type MarkdownReference,
  type MarkdownReferenceInspection,
  resolveMarkdownReference,
} from "./markdown-links.js";
export type { BlobStore } from "./ports/blob-store.js";
export type { Clock } from "./ports/clock.js";
export {
  allowEverything,
  type EntitlementAction,
  type EntitlementDecision,
  type EntitlementQuery,
  type Entitlements,
  type IndexLimits,
} from "./ports/entitlements.js";
export {
  type ArchiveFile,
  type ArchiveRequest,
  type GitHost,
  GitHostError,
  type GitHostErrorKind,
  type HostAccount,
  type HostCredential,
  type HostRepository,
  type RepoCoordinates,
  type RepoTree,
  type TreeEntry,
} from "./ports/git-host.js";
export type {
  GitHostDirectory,
  HostProfile,
  HostRepositoryListing,
  HostRepositoryPage,
} from "./ports/git-host-directory.js";
export {
  type GitHostDelivery,
  GitHostDeliveryError,
  type GitHostDeliveryProblem,
  type GitHostEvent,
  type GitHostEventSource,
  type HostEventScope,
} from "./ports/git-host-events.js";
export type {
  GitHostLogin,
  HostCredentials,
  HostInstallation,
  HostInstallations,
  HostInstalledRepository,
  HostUser,
} from "./ports/git-host-login.js";
export { discardUsage, type UsageEvent, type UsageSink } from "./ports/usage-sink.js";
export {
  baseName,
  classifyRepoFile,
  isExcludedPath,
  isHiddenPath,
  isReadmePath,
  isServedPath,
  nearestDirectoryAtOrAbove,
  owningSkillDirectory,
  parentDirectory,
  REPO_MANIFEST_FILE,
  type RepoFileKind,
  repoManifestPath,
  type ServedScope,
  SKILL_MANIFEST_FILE,
  selectReadmePaths,
} from "./repo-layout.js";
export {
  MAX_DOCUMENT_DIRECTORIES,
  MAX_EXCLUDED_PATHS,
  MAX_REPO_DESCRIPTION_LENGTH,
  MAX_REPO_MANIFEST_LENGTH,
  MAX_REPO_NAME_LENGTH,
  type ParsedRepoManifest,
  parseRepoManifest,
  type RepoImage,
  type RepoManifest,
  type RepoManifestError,
  type RepoManifestErrorCode,
  type RepoManifestWarning,
  type RepoManifestWarningCode,
  type RepoTranslation,
} from "./repo-manifest.js";
export {
  isWithinRepoPath,
  joinRepoPath,
  MAX_REPO_PATH_LENGTH,
  parseRepoPath,
  type RepoPath,
  type RepoPathError,
  type RepoPathErrorCode,
  ROOT_PATH,
  relativeRepoPath,
} from "./repo-path.js";
export {
  ACCOUNT_PAGE_PATH,
  AUTH_META_NAME,
  AUTH_ROUTES,
  CHOOSE_ACCOUNT_PARAM,
  CONSENT_ERROR_PARAM,
  CONSENT_PAGE_PATH,
  CONSENT_REQUEST_PARAM,
  loginPath,
  ownerRestPath,
  REPO_TOKEN_DEFAULT_DAYS,
  REPO_TOKEN_LIFETIMES_DAYS,
  REPO_TOKEN_MAX_DAYS,
  REPO_TOKEN_MAX_LABEL_LENGTH,
  REPO_TOKEN_PREFIX,
  RETURN_TO_PARAM,
  type RestAuthorization,
  type RestAuthorizationDecision,
  type RestGrants,
  type RestMe,
  type RestMyRepositories,
  type RestNewRepoToken,
  type RestOwner,
  type RestRepoTokenRequest,
  type RestRepoTokens,
  type RestUser,
  restAuthorizationDecisionSchema,
  restAuthorizationSchema,
  restGrantsSchema,
  restMeSchema,
  restMyRepositoriesSchema,
  restNewRepoTokenSchema,
  restOwnerSchema,
  restRepoTokenRequestSchema,
  restRepoTokensSchema,
  restUserSchema,
  SIGN_IN_ERROR_PARAM,
  SIGN_IN_FAILURES,
  SIGN_IN_PAGE_PATH,
  type SignInFailure,
  signInPagePath,
} from "./rest/account.js";
export {
  REST_FEATURED_SKILL_NAMES,
  REST_MOUNT_LIST_LIMIT,
  REST_ROUTES,
  type RestBrowse,
  type RestBrowseEntry,
  type RestDiagnostic,
  type RestDirectoryEntry,
  type RestDocumentSummary,
  type RestError,
  type RestFeatured,
  type RestFile,
  type RestFind,
  type RestFindItem,
  type RestFolderOverview,
  type RestLicense,
  type RestManifest,
  type RestMount,
  type RestReference,
  type RestRepository,
  type RestRepositoryCard,
  type RestRepoTranslation,
  type RestSkill,
  type RestSkillSummary,
  type RestSkillTranslation,
  restBrowseEntrySchema,
  restBrowseSchema,
  restDiagnosticSchema,
  restDirectoryEntrySchema,
  restDocumentSummarySchema,
  restErrorSchema,
  restFeaturedSchema,
  restFileSchema,
  restFindItemSchema,
  restFindSchema,
  restFolderOverviewSchema,
  restLicenseSchema,
  restMountSchema,
  restPath,
  restReferenceSchema,
  restRepositoryCardSchema,
  restRepositorySchema,
  restRepoTranslationSchema,
  restRepoTranslationsSchema,
  restSkillSchema,
  restSkillSummarySchema,
  restSkillTranslationSchema,
  restSkillTranslationsSchema,
} from "./rest/contracts.js";
export {
  isLegalDocumentKind,
  LEGAL_DOCUMENT_KINDS,
  LEGAL_PAGE_PATHS,
  type LegalDocumentInput,
  type LegalDocumentKind,
  type LegalTexts,
  legalDocumentInputSchema,
  legalPath,
  legalTextsSchema,
  MAX_LEGAL_BODY_LENGTH,
  type RestLegalDocument,
  restLegalDocumentSchema,
} from "./rest/legal.js";
export {
  completeShowcaseTexts,
  IMAGE_CONTENT_TYPES,
  MAX_MEDIA_BYTES,
  MEDIA_CONTENT_TYPES,
  MEDIA_ROUTE,
  mediaFitsSlot,
  mediaUrl,
  REFERENCE_REPOSITORY_ADDRESS,
  type RestShowcase,
  type RestShowcaseEntry,
  restShowcaseEntrySchema,
  restShowcaseSchema,
  SHOWCASE_ID_PATTERN,
  SHOWCASE_LANGUAGE_PATTERN,
  SHOWCASE_MEDIA_SLOTS,
  type ShowcaseDemo,
  type ShowcaseInput,
  type ShowcaseMedia,
  type ShowcaseMediaSlot,
  type ShowcaseTexts,
  type ShowcaseTextsInput,
  showcaseDemoSchema,
  showcaseInputSchema,
  showcaseMediaSchema,
  showcaseTextsInputSchema,
  showcaseTextsSchema,
  VIDEO_CONTENT_TYPES,
} from "./rest/showcase.js";
export {
  ICON_ROUTE,
  ICON_SIZE,
  SOCIAL_CARD_SIZE,
  SOCIAL_ROUTE,
  type SocialCard,
} from "./rest/social.js";
export { err, ok, type Result } from "./result.js";
export {
  assembleSkillDocument,
  frontMatterObject,
  type IncludedFileSection,
  type OmittedFile,
  omittedLines,
  provenanceLine,
  renderSkillSections,
  SKILLCDN_KEY,
  type SkillDocumentInput,
  type SkillRulesSection,
  type SkillSections,
  serializeFrontMatter,
} from "./skill-document.js";
export { type SkillDocumentSources, skillDocumentInput } from "./skill-document-sources.js";
export {
  describeListingProblem,
  describeOmittedFile,
  isHiddenSkill,
  SKILL_LISTING_MAX_BYTES,
  SKILL_LISTING_MAX_FILES,
  type SkillListingFile,
  type SkillListingInput,
  type SkillListingProblem,
  skillListingProblem,
} from "./skill-listing.js";
export {
  MAX_INCLUDED_FILES,
  MAX_SKILL_COMPATIBILITY_LENGTH,
  MAX_SKILL_DESCRIPTION_LENGTH,
  MAX_SKILL_MANIFEST_LENGTH,
  MAX_SKILL_NAME_LENGTH,
  MAX_SKILL_TITLE_LENGTH,
  type ParsedSkillManifest,
  parseSkillManifest,
  type SkillManifest,
  type SkillManifestContext,
  type SkillManifestError,
  type SkillManifestErrorCode,
  type SkillManifestWarning,
  type SkillManifestWarningCode,
  type SkillTranslation,
} from "./skill-manifest.js";
export {
  formatSkillUri,
  type ParsedSkillUri,
  parseSkillUri,
  SKILL_URI_SCHEME,
  type SkillUriAddress,
  skillUriPrefix,
} from "./skill-uri.js";
export { hasForbiddenCodePoint } from "./text-safety.js";
export {
  type CatalogManifest,
  type CatalogSkill,
  type CatalogState,
  catalogDescription,
  describeFindTool,
  FIND_DESCRIPTION_MAX_LENGTH,
  INSTRUCTIONS_MAX_LENGTH,
  type MountCatalog,
  renderInstructions,
} from "./tools/catalog.js";
export {
  BROWSE_DEFAULT_LIMIT,
  BROWSE_MAX_LIMIT,
  browseInputSchema,
  browseTool,
  FIND_DEFAULT_LIMIT,
  FIND_LIST_SKILLS_MAX,
  FIND_MAX_LIMIT,
  FIND_MAX_SKILL_FILES,
  getSkillInputSchema,
  getSkillTool,
  MAX_QUERY_LENGTH,
  MCP_BROWSE_DEFAULT_LIMIT,
  MCP_SEARCH_DEFAULT_LIMIT,
  READ_FILE_DEFAULT_LIMIT,
  READ_FILE_MAX_LIMIT,
  type ReadFileInput,
  readFileInputSchema,
  readFileTool,
  SKILL_PAGE_BYTES,
  searchInputSchema,
  searchTool,
  TOOL_NAMES,
  type ToolContract,
} from "./tools/contracts.js";
export {
  INDEXING_NOTICE,
  PROVENANCE_NOTICE,
  renderBrowseResult,
  renderDiagnostics,
  renderDirectoryResult,
  renderFileResult,
  renderFindResult,
  renderSkillResult,
} from "./tools/render.js";
export {
  BROWSE_DESCRIPTION_MAX_LENGTH,
  compactSummary,
  MCP_RESULT_MAX_BYTES,
  SEARCH_DESCRIPTION_MAX_LENGTH,
  serializedResultBytes,
} from "./tools/response-budget.js";
export type { BrowseEntry, BrowseResult, FileReference, FolderOverview } from "./tools/results.js";
export {
  type DirectoryEntry,
  type DirectoryResult,
  type FileResult,
  type FindFile,
  type FindItem,
  type FindResult,
  type IncludedFile,
  type IndexDiagnostic,
  MAX_SKILL_INCLUDED_LENGTH,
  MAX_SKILL_RULES_LENGTH,
  type MountSummary,
  pageOfText,
  type SkillResult,
  type SkillRules,
  type SkillServing,
} from "./tools/results.js";
