// Public surface of @skillcdn/core. Other workspaces import from this entry point only.
export { isAnonymouslyReadable } from "./access.js";
export {
  type Address,
  type AddressError,
  type AddressErrorCode,
  type AddressRef,
  formatAddress,
  GIT_HOST_KEYS,
  type GitHostKey,
  isPinnedAddress,
  MAX_ADDRESS_LENGTH,
  parseAddress,
} from "./address.js";
export { DomainError } from "./errors.js";
export {
  type FrontMatterError,
  type FrontMatterErrorCode,
  type FrontMatterSplit,
  MAX_FRONT_MATTER_LENGTH,
  parseFrontMatter,
  splitFrontMatter,
} from "./front-matter.js";
export { isFullCommitHash, isValidRefName, MAX_REF_LENGTH } from "./git-ref.js";
export { isLanguageTag, MAX_TRANSLATIONS } from "./manifest-fields.js";
export { type MarkdownSummary, summarizeMarkdown } from "./markdown.js";
export type { BlobStore } from "./ports/blob-store.js";
export type { Clock } from "./ports/clock.js";
export {
  allowEverything,
  type EntitlementAction,
  type EntitlementDecision,
  type EntitlementQuery,
  type Entitlements,
  type IndexLimits,
} from "./ports/entitlements.js";
export {
  type ArchiveFile,
  type ArchiveRequest,
  type GitHost,
  GitHostError,
  type GitHostErrorKind,
  type HostAccount,
  type HostRepository,
  type RepoCoordinates,
  type RepoTree,
  type TreeEntry,
} from "./ports/git-host.js";
export { discardUsage, type UsageEvent, type UsageSink } from "./ports/usage-sink.js";
export {
  baseName,
  classifyRepoFile,
  isHiddenPath,
  isServedPath,
  nearestDirectoryAtOrAbove,
  owningSkillDirectory,
  parentDirectory,
  REPO_MANIFEST_FILE,
  type RepoFileKind,
  repoManifestPath,
  type ServedScope,
  SKILL_MANIFEST_FILE,
} from "./repo-layout.js";
export {
  MAX_DOCUMENT_DIRECTORIES,
  MAX_REPO_DESCRIPTION_LENGTH,
  MAX_REPO_MANIFEST_LENGTH,
  MAX_REPO_NAME_LENGTH,
  type ParsedRepoManifest,
  parseRepoManifest,
  type RepoManifest,
  type RepoManifestError,
  type RepoManifestErrorCode,
  type RepoManifestWarning,
  type RepoManifestWarningCode,
  type RepoTranslation,
} from "./repo-manifest.js";
export {
  isWithinRepoPath,
  joinRepoPath,
  MAX_REPO_PATH_LENGTH,
  parseRepoPath,
  type RepoPath,
  type RepoPathError,
  type RepoPathErrorCode,
  ROOT_PATH,
  relativeRepoPath,
} from "./repo-path.js";
export {
  REST_FEATURED_SKILL_NAMES,
  REST_MOUNT_LIST_LIMIT,
  REST_ROUTES,
  type RestDiagnostic,
  type RestDirectoryEntry,
  type RestDocumentSummary,
  type RestError,
  type RestFeatured,
  type RestFile,
  type RestFind,
  type RestFindItem,
  type RestManifest,
  type RestMount,
  type RestRepository,
  type RestRepoTranslation,
  type RestSkill,
  type RestSkillSummary,
  type RestSkillTranslation,
  restDiagnosticSchema,
  restDirectoryEntrySchema,
  restDocumentSummarySchema,
  restErrorSchema,
  restFeaturedSchema,
  restFileSchema,
  restFindItemSchema,
  restFindSchema,
  restMountSchema,
  restPath,
  restRepositorySchema,
  restRepoTranslationSchema,
  restRepoTranslationsSchema,
  restSkillSchema,
  restSkillSummarySchema,
  restSkillTranslationSchema,
  restSkillTranslationsSchema,
} from "./rest/contracts.js";
export { err, ok, type Result } from "./result.js";
export {
  MAX_INCLUDED_FILES,
  MAX_SKILL_COMPATIBILITY_LENGTH,
  MAX_SKILL_DESCRIPTION_LENGTH,
  MAX_SKILL_MANIFEST_LENGTH,
  MAX_SKILL_NAME_LENGTH,
  MAX_SKILL_TITLE_LENGTH,
  type ParsedSkillManifest,
  parseSkillManifest,
  type SkillManifest,
  type SkillManifestContext,
  type SkillManifestError,
  type SkillManifestErrorCode,
  type SkillManifestWarning,
  type SkillManifestWarningCode,
  type SkillTranslation,
} from "./skill-manifest.js";
export { hasForbiddenCodePoint } from "./text-safety.js";
export {
  type CatalogManifest,
  type CatalogSkill,
  type CatalogState,
  describeFindTool,
  FIND_DESCRIPTION_MAX_LENGTH,
  INSTRUCTIONS_MAX_LENGTH,
  type MountCatalog,
  renderInstructions,
} from "./tools/catalog.js";
export {
  FIND_DEFAULT_LIMIT,
  FIND_LIST_SKILLS_MAX,
  FIND_MAX_LIMIT,
  FIND_MAX_SKILL_FILES,
  type FindInput,
  findInputSchema,
  findTool,
  type GetInput,
  getInputSchema,
  getTool,
  MAX_QUERY_LENGTH,
  READ_FILE_DEFAULT_LIMIT,
  READ_FILE_MAX_LIMIT,
  type ReadFileInput,
  readFileInputSchema,
  readFileTool,
  TOOL_NAMES,
  type ToolContract,
} from "./tools/contracts.js";
export {
  INDEXING_NOTICE,
  PROVENANCE_NOTICE,
  renderDiagnostics,
  renderDirectoryResult,
  renderFileResult,
  renderFindResult,
  renderSkillResult,
} from "./tools/render.js";
export {
  type DirectoryEntry,
  type DirectoryResult,
  type FileResult,
  type FindFile,
  type FindItem,
  type FindResult,
  type IncludedFile,
  type IndexDiagnostic,
  MAX_SKILL_INCLUDED_LENGTH,
  MAX_SKILL_RULES_LENGTH,
  type MountSummary,
  pageOfText,
  type SkillResult,
  type SkillRules,
} from "./tools/results.js";
